  export const GET_ALL_STARSHIPS = 'GET_ALL_STARSHIPS'
  export const CLEAR_STARSHIPS_LIST = 'CLEAR_STARSHIPS_LIST'

  export const GET_ALL_PEOPLE = 'GET_ALL_PEOPLE'
  export const CLEAR_PEOPLE_LIST = 'CLEAR_PEOPLE_LIST'