export const GET_ALL_STARSHIPS_LOADING = 'GET_ALL_STARSHIPS_LOADING'
export const GET_ALL_STARSHIPS_ERROR = 'GET_ALL_STARSHIPS_ERROR'
export const GET_ALL_STARSHIPS_SUCCESS = 'GET_ALL_STARSHIPS_SUCCESS'
export const CLEAR_STARSHIPS_LIST = 'CLEAR_STARSHIPS_LIST'